import type { SectionTemplate } from "./layout";

export const SECTION_TEMPLATES: SectionTemplate[] = [
  {
    id: "full-width",
    name: "Full Width",
    description: "Single column spanning full width",
    preview: "┌──────┐",
    columns: 1,
    columnWidths: ["100%"],
  },
  {
    id: "two-equal",
    name: "2 Equal Columns",
    description: "Two columns of equal width",
    preview: "┌──┐┌──┐",
    columns: 2,
    columnWidths: ["50%", "50%"],
  },
  {
    id: "three-equal",
    name: "3 Equal Columns",
    description: "Three columns of equal width",
    preview: "┌┐ ┌┐ ┌┐",
    columns: 3,
    columnWidths: ["33.33%", "33.33%", "33.34%"],
  },
  {
    id: "four-equal",
    name: "4 Equal Columns",
    description: "Four columns of equal width",
    preview: "┌┐┌┐┌┐┌┐",
    columns: 4,
    columnWidths: ["25%", "25%", "25%", "25%"],
  },
  {
    id: "sidebar-left",
    name: "Sidebar Left",
    description: "Narrow left column with wide content",
    preview: "┌┐┌───┐",
    columns: 2,
    columnWidths: ["25%", "75%"],
  },
  {
    id: "sidebar-right",
    name: "Sidebar Right",
    description: "Wide content with narrow right column",
    preview: "┌───┐┌┐",
    columns: 2,
    columnWidths: ["75%", "25%"],
  },
  {
    id: "two-one",
    name: "2/3 + 1/3",
    description: "Wide left, narrow right",
    preview: "┌───┐┌┐",
    columns: 2,
    columnWidths: ["66.66%", "33.34%"],
  },
  {
    id: "one-two",
    name: "1/3 + 2/3",
    description: "Narrow left, wide right",
    preview: "┌┐┌───┐",
    columns: 2,
    columnWidths: ["33.34%", "66.66%"],
  },
  {
    id: "hero",
    name: "Hero Section",
    description: "Full-width hero with centered content",
    preview: "┌──✧──┐",
    columns: 1,
    columnWidths: ["100%"],
  },
  {
    id: "feature-grid",
    name: "Feature Grid",
    description: "Three-column feature showcase",
    preview: "┌┐┌┐┌┐",
    columns: 3,
    columnWidths: ["33.33%", "33.33%", "33.34%"],
  },
];
